Unhandled exception: (terminating:true)
System.AggregateException: One or more errors occurred. (Broken pipe) ---> System.IO.IOException: Broken pipe
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.FlushInternalBuffer()
   at System.IO.FileStream.FlushAsyncInternal(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at FVim.neovim.proc.continuation@1-1(Stream stdin, TaskCompletionSource`1 src, Unit _arg6)
   at FVim.neovim.proc.call@208-4.Invoke(Unit unitVar0)
   at FSharp.Control.Tasks.TaskBuilder.StepStateMachine`1.nextAwaitable()
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInAnotherThread[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at FVim.Program.Main(String[] args)
---> (Inner Exception #0) System.IO.IOException: Broken pipe
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.FlushInternalBuffer()
   at System.IO.FileStream.FlushAsyncInternal(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at FVim.neovim.proc.continuation@1-1(Stream stdin, TaskCompletionSource`1 src, Unit _arg6)
   at FVim.neovim.proc.call@208-4.Invoke(Unit unitVar0)
   at FSharp.Control.Tasks.TaskBuilder.StepStateMachine`1.nextAwaitable()<---

